title: Jacob Lovatt
author: Jacob Lovatt
description: >-
  Posts about things I find interesting, that are sometimes useful too
url: "https://jacoblovatt.github.io"
baseurl: ""
timezone: "Europe/London"

# Theme
# Minima is actively maintained and supported on GitHub Pages.
theme: minima

minima:
  skin: classic
  social_links:
    - title: Jacob Lovatt on GitHub
      icon: github
      url: "https://github.com/jacoblovatt"

header_pages:
  - aboutme.md
  - blog.html
  - recommendedreading.md
  - tags.html

markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
date_format: "%B %-d, %Y"

kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
  -
    scope:
      path: ""
    values:
      layout: page

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - legacy/
